Artist page
i-karshev/fwt-art-gallery pull request #8
Opened 2023-05-04 09:33 UTC by i-karshev

2023-05-11 15:19 UTC, lgnvk commented on src/components/ArtistInfo/ArtistInfo.tsx
> +export const ArtistInfo: FC<ArtistInfoProps> = ({ artist, isDarkTheme }) => (
Можно деструктурировать artist: {} и достать оттуда всё что надо по аналогии с другими компонентами

2023-05-11 15:24 UTC, lgnvk commented on src/components/Gallery/Gallery.tsx
> +          artists.map((artist) => (
Можно деструктуризировать artists

2023-05-11 15:34 UTC, lgnvk commented on src/components/Slider/Slider.tsx
> +  const handleScrollToPrevSlide = () => {
У тебя по сути handleSrollToNextSlide и handleSrollToPrevSlide отличаются только в slideWidth + 1/slideWidtth - 1, можно объединить в один метод handleScroll, и пробрасывать + 1 или - 1 аргументом, избавишься от дублирования кода

2023-05-11 15:36 UTC, lgnvk commented on src/components/Slider/Slider.tsx
> +            paintings.map((painting, index) => (
Можно деструктуризировать painting

2023-05-11 15:42 UTC, lgnvk commented on src/components/Slider/Slider.tsx
> +            paintings.map((painting, index) => (
И дальше по коду тоже посмотри где можно исправить

2023-05-16 12:24 UTC, lightsout1993 commented on src/components/ArtistAccordion/ArtistAccordion.module.scss
> +    -webkit-text-fill-color: transparent;
повторяется

2023-05-16 12:58 UTC, lightsout1993 requested changes

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ArtistAccordion/ArtistAccordion.tsx
> +          'artist-accordion__text_full': !isShowAccordion || isOpenAccordion,
`!isShowAccordion || isOpenAccordion` - это в переменную, есть повтор ниже, назови это как-то условие, чтобы было понятно, что это за кейс

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ArtistInfo/ArtistInfo.module.scss
> +    }
пустая строка, разделяй блоки стилей пустыми строками, повышает читаемость

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ArtistInfo/ArtistInfo.module.scss
> +      min-height: 1000px;
посмотри

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ArtistInfo/ArtistInfo.tsx
> +import styles from './ArtistInfo.module.scss';
отдели пробелом последний импорт
поряд такой: 
1) типы из либ. потом либы, потом потом пробел
2) типы с алиасами, потом алисы, потом пустая строка
3) типы из этой же папки, потом импорты из этой же папки

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ArtistInfo/ArtistInfo.tsx
> +  artist: { name, avatar, description, genres, yearsOfLife },
давай тут в объект не объединять, передай это отдельными пропсами

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ArtistInfo/ArtistInfo.tsx
> +            src={`${API_BASE_URL}${avatar.webp}`}
src-set юзай

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ScrollToTop/ScrollToTop.module.scss
> +    &:hover {
пустая строка между 26 и 27

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ScrollToTop/ScrollToTop.tsx
> +export const ScrollToTop: FC<ScrollToTopProps> = ({ isDarkTheme }) => (
тут логику скролла вверх тоже опиши

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/Slider/Slider.tsx
> +      bodyRef.current.style.overflow = 'auto';
это перенести в модалку и добавить паддинг, шириной с полосу прокрутки

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/Slider/Slider.tsx
> +import { createPortal } from 'react-dom';
этот импорт не там, он библиотечный

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/Slider/Slider.tsx
> +import { API_BASE_URL } from '@/constans';
ui-component

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Button/Button.module.scss
> +        background-color: #ba9052;
в переменную?

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Label/Label.module.scss
> +    font-family: 'Inter', sans-serif;
перенеси в родитель

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Label/Label.tsx
> +    {!!onClose && (
`onClose ?? (`

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Modal/Modal.module.scss
> +  background-color: rgba(3, 3, 3, 0.3);
3, 3, 3 - в hex и переменную
в sass можно в rgba hex вставлять

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Modal/Modal.tsx
> +      bodyRef.current.style.overflow = 'auto';
тут замечания написал в слайдере уже

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Preloader/Preloader.module.scss
> +@keyframes ellipse-4 {
пустая строка

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/Slider/Slider.tsx
> +import { ReactComponent as CloseIcon } from '@/assets/svg/close_icon.svg';
ассеты всегда ниже, чем компоненты

2023-05-16 12:58 UTC, lightsout1993 commented on src/components/ui/Modal/Modal.tsx
> +        X
это svg

2023-05-16 12:58 UTC, lightsout1993 commented on src/pages/ArtistPage/ArtistPage.tsx
> +  const handleCloseSlider = () => {
заворачивай такие методы в useCallback
пропсы для ui компонентов в useMemo если требуется
а ui компоненты должны быть обернуты в memo

2023-05-16 12:58 UTC, lightsout1993 commented on src/pages/ArtistPage/ArtistPage.tsx
> +  };
```
const handleShowSlider = (index: number) => () => {
    setCurrentIndex(index);
    setIsShowSlider(true);
  };
```
и в useCallback

2023-05-16 12:58 UTC, lightsout1993 commented on src/pages/ArtistPage/ArtistPage.tsx
> +                      onClick={() => handleShowSlider(index)}
а тут 
`onClick={handleShowSlider(index)}`

2023-05-17 14:03 UTC, i-karshev commented on src/components/ArtistAccordion/ArtistAccordion.module.scss
> +    -webkit-text-fill-color: transparent;
без повторения не работает

2023-05-17 14:28 UTC, i-karshev commented on src/components/ArtistInfo/ArtistInfo.module.scss
> +      min-height: 1000px;
убрал height: auto; , min-height: 1000px; нужен чтобы задать минимальную высоту контейнера, чтобы контент который ниже не наезжал на картинку, так как она позиционирована абсолютно.

2023-05-25 11:59 UTC, lightsout1993 approved these changes

2023-05-25 12:00 UTC, merged